apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/qasimnauman-emumba/voting-app-k8s.git
    targetRevision: production
    path: k8s/backend
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
