apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/qasimnauman-emumba/voting-app-k8s.git
    targetRevision: production
    path: k8s
    directory:
      include: "namespace.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
